### ISSUE TITLE
code block does not work

### ISSUE THREAD

**Issue by CatNofishing** [sweatran/typora-onedark-theme#2] opened 2020-05-15 04:40 UTC
code block does not work

**Comment by sweatran** [comment] 2020-05-15 06:44
Please give me more details about your problem (e.g. your platform, the version of Typora, the markdown codes that cause the problem, etc.)

**Comment by yohaoquan** [comment] 2020-05-15 07:59
I just experienced the problem I believe @CatNofishing is talking about. Lemme fill the void for them.

The code blocks do not disappear when enabling the source code mode(cmd + /)

I am using Typora  Version 0.9.9.32.1 (4191) Beta on Mac.
Please see the images below.
Love your theme. Hope the line spacing is just a little bit larger :)

<img width="949" alt="Screen Shot 2020-05-15 at 3 57 33 AM" src="https://user-images.githubusercontent.com/16907613/82026263-87f18280-9660-11ea-8992-9bf2b7ee731c.png">
<img width="950" alt="Screen Shot 2020-05-15 at 4 02 47 AM" src="https://user-images.githubusercontent.com/16907613/82026600-f6364500-9660-11ea-9116-cac833be3b64.png">

**Comment by sweatran** [comment] 2020-05-15 08:40
@yohaoquan I'm afraid that I cannot help you cuz I don't have any Apple devices. The code block in source code mode works fine on Windows though, so I think some html of Typora is different on Mac, which cause the problem. I‘ll try to fix it if I have any chance to use a Mac. 

(BTW, The underlying html of Typora is much "dirtier" than its final UI apperence. They even use different code styles for each panels and menus... )

For adjusting line spacing, you can change the `line-height` value in the following code in `onedark.css`. The default is 1.6.
```
body {
    font-family: "Open Sans", "Clear Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
    color: var(--text-color1);
    background: var(--bg-color1);
    line-height: 1.6;
}
```

**Comment by yohaoquan** [comment] 2020-05-15 08:53
@sweatran thanks for the info! That's quite unfortunate to hear actually. I expected this app to be written beautifully inside given how good looking its outside is. Is it easy for you to explain how you handled the show/hide logic of the code block if you handled it? I could give fixing it a quick try

**Comment by sweatran** [comment] 2020-05-15 09:55
@yohaoquan I may find the way to fix it.
Try changing the followings:
```
:not(.typora-sourceview-on) #write {
    visibility: visible;
    opacity: 1;
}
```
to this:
```
body.typora-node:not(.typora-sourceview-on) #write {
    visibility: visible;
    opacity: 1;
}
```
Here is how it goes: 
When source mode is enabled, Typora will add a class called `typora-sourceview-on` to its `body` tag. By default, Typora use `display` property to control the show/hide of source code menu (the id is `typora-source`). To add the fade in/out effect, I override the `display` to `block` and use `visibility` and `opacity` property instead, like the following:
```
#typora-source {
    display: block !important;
    visibility: hidden;
    opacity: 0;
    transition: 0.3s;
}
/* This selector has a higher priority than the upper one when source mode enabled*/
/* So it will override the visibility and opacity */ 
.typora-sourceview-on #typora-source {
    visibility: visible;
    opacity: 1;
}
```
However, I found that the selector for `#write`  was not proper and it never disappeared. On Windows the source code menu is above `#write` , so everything is OK. Maybe on Mac only code block in `#write` is special.

**Comment by yohaoquan** [comment] 2020-05-16 21:13
I just had time to try the code change you proposed. Unfortunately, it raised more questions than it answered. The whole body is now hidden when the source mode is off.

<img width="1072" alt="Screen Shot 2020-05-16 at 5 03 28 PM" src="https://user-images.githubusercontent.com/16907613/82130188-2d0e7700-9797-11ea-8731-eba4b1efa603.png">


Now I must admit that I do not have much experience in CSS and this solution may be redundant and not work on windows.

I think the original code didn't work because the #write's opacity and visibility was never changed when getting into source-mode.
I seem to have fixed it by adding another argument after the one that's previously in there to it becomes:

```css
:not(.typora-sourceview-on) #write {
    visibility: visible;
    opacity: 1;
}

.typora-sourceview-on #write {
    visibility: hidden;
    opacity: 0;
}
```
But this raised more questions. Why is it working on Windows without this second one?

Also, when comparing your theme with other built-in ones like the GitHub theme, I found that the caret's position was not transferred when switching modes. Is this also a function that needs to be handled?

btw, I changed the line spacing to 1.8 and it feels so much better imo :)

**Comment by sweatran** [comment] 2020-06-15 16:11
Sorry that I'm quite busy in the last month and have no time to deal with this issue. The different behaviours between Windows and Mac is caused by different HTML codes. Because I don't have the HTML on Mac, I can't say what exactly cause this. Anyway, I've updated the files based on your solution. Please check if the new version works fine or not.
btw, what does the "caret's position" means? Is it means the markdown syntax for superscipts?

**Comment by atomicpages** [comment] 2020-07-28 15:53
Code blocks with fine on macOS :+1:

Typora: 0.9.9.34.2 (4509)
typora-onedark-theme: 1.01

**Closed as completed** 2020-07-29 09:17 UTC
